config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post   '/',        to: 'microposts#create'   
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def new
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end 
  end
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/new.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
           <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div id ="feed" class="col-md-8">
      <h2>Micropost Feed</h2>
      <%= render 'shared/feed' %>
    </div>
  </div>

<% else %>

<div id="home" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#home" data-slide-to="0" class="active"></li>
      <li data-target="#home" data-slide-to="1"></li>
      <li data-target="#home" data-slide-to="2"></li>
      <li data-target="#home" data-slide-to="3"></li>
      <li data-target="#home" data-slide-to="4"></li>
      <li data-target="#home" data-slide-to="5"></li>
      <li data-target="#home" data-slide-to="6"></li>
      <li data-target="#home" data-slide-to="7"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag("szarjah1.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Sharjah, UAE</h3>
          <p>The Dancing Fountain</p>
        </div>      
      </div>

      <div class="item">
         <%= image_tag("singapur_garden2.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Singapur</h3>
          <p>Garden by the Bay</p>
        </div>      
      </div>
    
      <div class="item">
        <%= image_tag("singapur_marina1.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Singapur</h3>
          <p>Singapur Marina</p>
        </div>      
      </div>

    <div class="item">
         <%= image_tag("singapur_garden1.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Singapur</h3>
          <p>Garden by the Bay</p>
        </div>      
      </div>
    
      <div class="item">
        <%= image_tag("singapur_garden3.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Singapur</h3>
          <p>Garden by the Bay</p>
        </div>      
      </div>

      <div class="item">
        <%= image_tag("dubai_marina1.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Dubai</h3>
          <p>Dubai Marina</p>
        </div>      
      </div>

    <div class="item">
         <%= image_tag("dubai_mall1.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Dubai</h3>
          <p>Dubai Fountain</p>
        </div>      
      </div>
    
      <div class="item">
        <%= image_tag("dubai_madinat1.jpg", alt: "Rails logo", size: "1200x700") %>
        <div class="carousel-caption description">
          <h3>Dubai</h3>
          <p>Madinat Jumeirah</p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#home" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#home" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
<br>
<div id="about" class="container text-justify">
    <h1>Welcome to the Cur1osity.com</h1>
    <br>
<p class ="slideanim">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." </p>

  </div>

   <p class ="text-center"> <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary slideanim" %> </p>
<br>
<div id="log_in" clas="container">
<h2>Log in</h2>
<div class="row slideanim">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, placeholder: "Enter your email", required: true, class: 'form-control' %>

      <%= f.label :password %>
      <%= link_to "(Forgot password?)", new_password_reset_path %>
      <%= f.password_field :password, placeholder: "Enter your password", required: true, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline remember" do %>
        <%= f.check_box :remember_me %>
        <span>Remember me on this computer</span>
      <% end %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

<div id="contact" class="container">
  <h2>Contact</h2>
  <br>
  <div class="row slideanim">
    <div class="col-md-6 col-md-offset-3">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea>
      <br>
      <div class="row">
        <div class="col-md-12 col-md-offset-10 form-group">
          <button class= "btn btn-primary" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip(); 
  
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });

 $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})

</script>

<!-- Add Google Maps -->
<!-- <div id="googleMap"></div>

    <script>
function myMap() {
var myCenter = new google.maps.LatLng(52.229797, 21.011755);
var mapProp = {center:myCenter, zoom:12, scrollwheel:false, draggable:false, mapTypeId:google.maps.MapTypeId.ROADMAP};
var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
var marker = new google.maps.Marker({position:myCenter});
marker.setMap(map);
}
</script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0VLBXIga8jpFbosaipP57nRWKUr77k6M&callback=myMap"></script>
-->

<% end %>