config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#new'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post   '/',        to: 'microposts#create'   
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
  <div class="navbar-header">
  <canvas id="canvas" width="80" height="40" style="cursor: pointer;" onclick="window.location='/';"></canvas>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar2">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar2">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, class: 'black_link' %></li>
        <li><%= link_to "Users", users_path, class: 'black_link' %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle black_link" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user, class: 'other_links' %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: 'other_links' %></li>
              <li><%= link_to "Log out", logout_path, method: :delete, class: 'log_out_link' %></li>
              <li class="divider"></li>
              <li><%= link_to "Delete account", current_user, method: :delete, class: 'delete_link',
             data: { confirm: "Are you sure?" } %></li>
            </ul>
      </ul>
  </div>
</div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
   <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="150">

 <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
         <% end %>
 
 <% if logged_in? %>

  <%= render 'layouts/header' %>
 
  <div class="container">

  <%= yield %>

  </div>

 <% else %> 

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
     <div class="navbar-header">
     <canvas id="canvas" width="80" height="40" style="cursor: pointer;" onclick="window.location='/';"></canvas>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right navbar-custom">

      <% if current_page?(root_path) %>
  
        <li><%= link_to "Home", '#home' %></li>
        <li><%= link_to "About",   '#about' %></li>
        <li><%= link_to "Log in", '#log_in' %></li>
        <li><%= link_to "Contact", '#contact' %></li>
        <li><%= link_to "Sign up", signup_path %></li>
      
      <% elsif current_page?(login_path) %>

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>

      <% elsif current_page?(signup_path) %>

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Log in", login_path %></li>

      <% else %>

        <li><%= link_to "Home", root_path %></li>
       
      <% end %>

      </ul>
    </div>
  </div>
</nav>

  <%= yield %>

 <% end %>

    </div>

<!-- Footer -->
<footer class="text-center">
  <a class="up-arrow" href="#" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a><br><br>
  <p>By <a href="https://www.cur1osity.com" data-toggle="tooltip" title="www.cur1osity.com">www.cur1osity.com</a></p> 
</footer>

<script>
var canvas = document.getElementById("canvas"); 
var ctx = canvas.getContext("2d");
  ctx.font = "100 40px Ruge Boogie"; 
  ctx.fillStyle = 'black';
  ctx.fillText("</   >", 0, 40);
  ctx.font = "100 46px Ruge Boogie";
  ctx.fillStyle = 'red';
  ctx.fillText("?", 37, 40);
</script>

  </body>
</html>